spring.application.name=demo

# URL de conexión (cambia 'nombre_de_la_bd' por el nombre que le vayas a poner a tu proyecto)
spring.datasource.url=jdbc:mysql://localhost:3306/madre-zoraida

# Tu usuario y contraseña de MySQL (por defecto en XAMPP es root sin contraseña, o en Workbench suele ser root/root)
spring.datasource.username=root
spring.datasource.password=1234

# El driver que permite la conexión
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate: Esto creará o actualizará las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true